crearCuenta = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[2]/a'
email = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[1]/div[1]/input'
telefono = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[1]/div[2]/input'
password = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[2]/div[1]/input'
mostrar1 = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[2]/div[1]/span/span[1]'
ocultar1 = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[2]/div[1]/span/span[2]'
password2 = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[2]/div[2]/input'
mostrar2 = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[2]/div[2]/span/span[1]'
ocultar2 = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[1]/div[2]/div[2]/span/span[2]'
TyC = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[2]/label/app-modalterms/p/a'
cerrar = '/html/body/ngb-modal-window/div/div/div[3]/button'
AvisosPrivacidad = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[2]/label/app-modal-privacy/p/a'
cookies = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[1]/div[2]/label/app-modal-cookies/p/a'
legales = '//*[@id="checkbox_terms"]'
continuar = '/html/body/app-root/app-login/div/div/div/div[4]/form/div[2]/button'

