facturacion = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[1]/div/div/div/ul/li[3]'
razonSocial = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[1]/div/input'
rfc = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[2]/div/input'
regimenFiscal = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[3]/div/select'
CFDI = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[4]/div/select'
codigoPostal = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[5]/div/input'
recordatorios = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[6]/div/label'
actualizar = '/html/body/app-root/app-dashboard/div/app-configuration-dashboard/div/div/div/div[2]/div/app-configuration-billing/div/div/form/div[7]/div/button'