addPregunta = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[2]/div/button'
expLaboral = '//*[@id="checkboxes"]/div[1]/label'
expPregunta = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[3]/div/div[2]/div/div[1]/div/input'
comboBox1 = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[3]/div/div[1]/div/div[2]/select'
expSi= '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[3]/div/div[2]/div/div[2]/div/div/label[1]/input'
expNo = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[3]/div/div[2]/div/div[2]/div/div/label[2]/input'
hDura = '//*[@id="checkboxes"]/div[2]/label'
duraPregunta = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[4]/div/div[2]/div/div[1]/div/input'
comboBox2 = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[4]/div/div[1]/div/div[2]/select'
yearExp = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[4]/div/div[2]/div/div[2]/div/div/input'
hBlanda = '//*[@id="checkboxes"]/div[3]/label'
blandaPrgunta = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[5]/div/div[2]/div/div[1]/div/input'
comboBox3 = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[5]/div/div[1]/div/div[2]/select'
blandaSi = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[5]/div/div[2]/div/div[2]/div/div/label[1]/input'
blamdaNo = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[2]/div/div/div[5]/div/div[2]/div/div[2]/div/div/label[2]/input'
siguiente = '/html/body/app-root/app-dashboard/div/app-crear-vacante/div/div[1]/app-requeriments2/div[3]/div/div/div[2]/button[2]'