clientes = '//*[@id="sidebar"]/ul/li[4]/a'
nuevo = '/html/body/app-root/app-dashboard/div/app-clients/app-main-navbar/div/div/div[3]/button'
nombreCliente = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[2]/div/input'
sector = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[3]/div/div/select'
giro = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[4]/div/div/select'
tipoEmpresa = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[5]/div/div/select'
cantidad1a10 = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[6]/div/div/div/button[1]'
cantidad11a50 = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[6]/div/div/div/button[2]'
cantidad51a250 = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[6]/div/div/div/button[3]'
cantidad250 = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[2]/form/div[6]/div/div/div/button[4]'
guardar = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[3]/span[1]'
cerrar = '/html/body/ngb-modal-window/div/div/app-modal-new-client/div[3]/span[2]'
hambuguesa = '//*[@id="dropdownClient"]'
eliminar = '//*[@id="tableCerradas"]/tbody/tr[1]/td[8]/div/div/button[2]'
cancelar = '/html/body/ngb-modal-window/div/div/div/div[3]/span[1]'
eliminar2 =  '/html/body/ngb-modal-window/div/div/div/div[3]/span[2]'

